### ISSUE TITLE
Python error AssertionError: Observation space ... does not inherit from gym.spaces.Space

### ISSUE THREAD

**Issue by nickponline** [utilForever/baba-is-auto#43]
```
(dev) [nickp@m1 baba-babaisyou-v0 (main)]$ python3 DQN.py 
```

```
Traceback (most recent call last):
  File "DQN.py", line 16, in <module>
    env = gym.make('baba-babaisyou-v0')
  File "/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/gym/envs/registration.py", line 601, in make
    env = PassiveEnvChecker(env)
  File "/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 25, in __init__
    check_observation_space(env.action_space)
  File "/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 145, in check_observation_space
    f"Observation space ({observation_space}) does not inherit from gym.spaces.Space"
AssertionError: Observation space ([<Direction.UP: 1>, <Direction.DOWN: 2>, <Direction.LEFT: 3>, <Direction.RIGHT: 4>]) does not inherit from gym.spaces.Space
```

```
Python 3.7.10
gym.__version__ = '0.24.1'
```

**Comment by utilForever** [comment]
Thanks for report! I'll check it tonight. 😉

**Comment by thesssssupdude** [comment]
Hi,
I ran into the same issue and I believe it is due to gym being updated to a later version which is more strict regarding the creation of new environments.

**Comment by BrianPark314** [comment]
does anyone know how to update the code to match the lateest version?

**Comment by utilForever** [comment]
Sorry for very late response. I fixed this bug in https://github.com/utilForever/baba-is-auto/pull/92.
